#!/bin/bash
sudo mount /dev/sdb1 /mnt/BOOT
sudo cp ~/vmware-shared/zedboard/images/BOOT.BIN /mnt/BOOT/
sudo cp ~/vmware-shared/zedboard/images/ramdisk8M.image.gz /mnt/BOOT/
sudo cp ~/linux-digilent/devicetree.dtb /mnt/BOOT/
sudo cp ~/linux-digilent/arch/arm/boot/zImage /mnt/BOOT/
sudo umount /mnt/BOOT
